CREATE TABLE lotofacil_numeros_sorteados_cp (
	LFNSCP_CODIGO int(11) AUTO_INCREMENT NOT NULL,
	LFNSCP_B1 VARCHAR(02)	NOT NULL,
	LFNSCP_B2 VARCHAR(02)	NOT NULL,
	LFNSCP_B3 VARCHAR(02)	NOT NULL,
	LFNSCP_B4 VARCHAR(02)	NOT NULL,
	LFNSCP_B5 VARCHAR(02)	NOT NULL,
	LFNSCP_B6 VARCHAR(02)	NOT NULL,
	LFNSCP_B7 VARCHAR(02)	NOT NULL,
	LFNSCP_B8 VARCHAR(02)	NOT NULL,
	LFNSCP_B9 VARCHAR(02)	NOT NULL,
	LFNSCP_B10 VARCHAR(02) NOT NULL,
	LFNSCP_B11 VARCHAR(02) NOT NULL,
	LFNSCP_B12 VARCHAR(02) NOT NULL,
	LFNSCP_B13 VARCHAR(02) NOT NULL,
	LFNSCP_B14 VARCHAR(02) NOT NULL,
	LFNSCP_B15 VARCHAR(02) NOT NULL,
	PRIMARY KEY(LFNSCP_CODIGO)
);

CREATE TABLE lotofacil_numeros_sorteados (
	LFNS_CODIGO int(11) AUTO_INCREMENT NOT NULL,
	LFNS_B1 VARCHAR(02)	NOT NULL,
	LFNS_B2 VARCHAR(02)	NOT NULL,
	LFNS_B3 VARCHAR(02)	NOT NULL,
	LFNS_B4 VARCHAR(02)	NOT NULL,
	LFNS_B5 VARCHAR(02)	NOT NULL,
	LFNS_B6 VARCHAR(02)	NOT NULL,
	LFNS_B7 VARCHAR(02)	NOT NULL,
	LFNS_B8 VARCHAR(02)	NOT NULL,
	LFNS_B9 VARCHAR(02)	NOT NULL,
	LFNS_B10 VARCHAR(02) NOT NULL,
	LFNS_B11 VARCHAR(02) NOT NULL,
	LFNS_B12 VARCHAR(02) NOT NULL,
	LFNS_B13 VARCHAR(02) NOT NULL,
	LFNS_B14 VARCHAR(02) NOT NULL,
	LFNS_B15 VARCHAR(02) NOT NULL,
	PRIMARY KEY(LFNS_CODIGO)
);

CREATE TABLE lotofacil_numeros_apostados  (
	LFNA_CODIGO int(11) AUTO_INCREMENT NOT NULL,
	LFNA_B1 VARCHAR(02)	NOT NULL,
	LFNA_B2 VARCHAR(02)	NOT NULL,
	LFNA_B3 VARCHAR(02)	NOT NULL,
	LFNA_B4 VARCHAR(02)	NOT NULL,
	LFNA_B5 VARCHAR(02)	NOT NULL,
	LFNA_B6 VARCHAR(02)	NOT NULL,
	LFNA_B7 VARCHAR(02)	NOT NULL,
	LFNA_B8 VARCHAR(02)	NOT NULL,
	LFNA_B9 VARCHAR(02)	NOT NULL,
	LFNA_B10 VARCHAR(02) NOT NULL,
	LFNA_B11 VARCHAR(02) NOT NULL,
	LFNA_B12 VARCHAR(02) NOT NULL,
	LFNA_B13 VARCHAR(02) NOT NULL,
	LFNA_B14 VARCHAR(02) NOT NULL,
	LFNA_B15 VARCHAR(02) NOT NULL,
	PRIMARY KEY(LFNA_CODIGO)
);

